name: CI
on:
  push:
    paths-ignore:
      - "docs/**"
      - "book/**"
      - "**.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "book/**"
      - "**.md"

env:
  RUSTFLAGS: "-D warnings"

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: fmt
        run: cargo fmt --all -- --check
  
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: cache
        uses: Swatinem/rust-cache@v2

      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest ]
        rust: [stable, beta, nightly]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: cache
        uses: Swatinem/rust-cache@v2

      - name: test
        run: cargo test --all-targets --all-features